"""create domain tables for phases 9-52

Explicit DDL for every ORM table registered on ``Base.metadata`` that was not
covered by 0001. Previously these tables were only materialized lazily at
runtime via ``ensure_tables()`` / ``Base.metadata.create_all``; this revision
makes ``alembic upgrade head`` produce the complete schema on a clean database.

Revision ID: 0002_domain_tables
Revises: 0001_core_foundation
Create Date: 2026-05-22
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002_domain_tables'
down_revision: str | None = '0001_core_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Sentinel used to detect databases that predate this revision and were
# materialized by the legacy runtime ``Base.metadata.create_all`` path.
_ADOPTION_SENTINEL_TABLE = "action_suggestions"


def upgrade() -> None:
    # Adoption guard: deployments created before this revision already have
    # these tables (built lazily at runtime via ``ensure_tables`` /
    # ``create_all``). Re-issuing CREATE TABLE would fail with "relation
    # already exists", so for those databases this revision is stamp-only;
    # any genuinely missing table is still filled in by the runtime
    # ``ensure_tables`` fallback. Clean databases (CI, new installs) take the
    # normal DDL path below.
    inspector = sa.inspect(op.get_bind())
    if _ADOPTION_SENTINEL_TABLE in set(inspector.get_table_names()):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=False),
    sa.Column('instrument_scope', sa.String(length=32), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('option_expression_status', sa.String(length=32), nullable=False),
    sa.Column('manual_option_input_needed', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('suggested_action_summary', sa.Text(), nullable=False),
    sa.Column('confidence_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('entry_condition_json', sa.JSON(), nullable=False),
    sa.Column('option_contract_criteria_json', sa.JSON(), nullable=True),
    sa.Column('invalidation_condition_json', sa.JSON(), nullable=False),
    sa.Column('upgrade_condition_json', sa.JSON(), nullable=False),
    sa.Column('downgrade_condition_json', sa.JSON(), nullable=False),
    sa.Column('watch_condition_json', sa.JSON(), nullable=False),
    sa.Column('next_review_trigger_json', sa.JSON(), nullable=False),
    sa.Column('decision_trace_json', sa.JSON(), nullable=False),
    sa.Column('version_stamp_json', sa.JSON(), nullable=False),
    sa.Column('action_items_json', sa.JSON(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_action_suggestions_symbol_date')
    )
    op.create_index(op.f('ix_action_suggestions_id'), 'action_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_action_suggestions_symbol'), 'action_suggestions', ['symbol'], unique=False)
    op.create_index('ix_action_suggestions_symbol_date', 'action_suggestions', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('api_key_env', sa.String(length=128), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key', name='uq_ai_providers_provider_key')
    )
    op.create_index(op.f('ix_ai_providers_id'), 'ai_providers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_providers_provider_key'), 'ai_providers', ['provider_key'], unique=True)
    op.create_table('case_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('case_type', sa.String(length=48), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('outcome_type', sa.String(length=48), nullable=True),
    sa.Column('option_data_available', sa.Boolean(), nullable=False),
    sa.Column('lesson_summary', sa.Text(), nullable=True),
    sa.Column('decision_context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_case_memory_source')
    )
    op.create_index(op.f('ix_case_memory_id'), 'case_memory', ['id'], unique=False)
    op.create_index(op.f('ix_case_memory_symbol'), 'case_memory', ['symbol'], unique=False)
    op.create_index('ix_case_memory_symbol_type', 'case_memory', ['symbol', 'case_type'], unique=False)
    op.create_table('data_freshness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('latest_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_status', sa.String(length=50), nullable=False),
    sa.Column('max_age_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_freshness_data_category'), 'data_freshness', ['data_category'], unique=True)
    op.create_index(op.f('ix_data_freshness_id'), 'data_freshness', ['id'], unique=False)
    op.create_table('data_schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_data_schema_versions')
    )
    op.create_index(op.f('ix_data_schema_versions_id'), 'data_schema_versions', ['id'], unique=False)
    op.create_table('decision_audit_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('version_stamp_json', sa.JSON(), nullable=False),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.Column('missing_version_keys_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_decision_audit_symbol_date')
    )
    op.create_index(op.f('ix_decision_audit_metadata_id'), 'decision_audit_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_decision_audit_metadata_symbol'), 'decision_audit_metadata', ['symbol'], unique=False)
    op.create_index('ix_decision_audit_symbol_date', 'decision_audit_metadata', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('decision_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('final_label', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('stock_thesis_label', sa.String(length=64), nullable=False),
    sa.Column('option_expression_label', sa.String(length=64), nullable=False),
    sa.Column('instrument_scope', sa.String(length=32), nullable=False),
    sa.Column('event_risk_level', sa.String(length=16), nullable=False),
    sa.Column('memory_risk_level', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('checklist_json', sa.JSON(), nullable=False),
    sa.Column('trace_json', sa.JSON(), nullable=False),
    sa.Column('version_stamp_json', sa.JSON(), nullable=False),
    sa.Column('sufficiency_decision_json', sa.JSON(), nullable=False),
    sa.Column('hard_filter_decision_json', sa.JSON(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('option_data_requested', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_decision_snapshots_symbol_date')
    )
    op.create_index(op.f('ix_decision_snapshots_id'), 'decision_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_decision_snapshots_symbol'), 'decision_snapshots', ['symbol'], unique=False)
    op.create_index('ix_decision_snapshots_symbol_date', 'decision_snapshots', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('do_not_touch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('freeze_category', sa.String(length=64), nullable=False),
    sa.Column('freeze_severity', sa.String(length=32), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('source_phase', sa.String(length=64), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_do_not_touch_history_event_type'), 'do_not_touch_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_do_not_touch_history_id'), 'do_not_touch_history', ['id'], unique=False)
    op.create_index(op.f('ix_do_not_touch_history_symbol'), 'do_not_touch_history', ['symbol'], unique=False)
    op.create_index('ix_do_not_touch_history_symbol_created', 'do_not_touch_history', ['symbol', 'created_at'], unique=False)
    op.create_table('do_not_touch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('freeze_category', sa.String(length=64), nullable=False),
    sa.Column('freeze_severity', sa.String(length=32), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_kind', sa.String(length=32), nullable=False),
    sa.Column('release_condition_label', sa.String(length=128), nullable=False),
    sa.Column('release_condition_description', sa.Text(), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=False),
    sa.Column('source_phase', sa.String(length=64), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_do_not_touch_items_symbol')
    )
    op.create_index('ix_do_not_touch_items_active', 'do_not_touch_items', ['is_active'], unique=False)
    op.create_index('ix_do_not_touch_items_expires', 'do_not_touch_items', ['expires_at'], unique=False)
    op.create_index(op.f('ix_do_not_touch_items_id'), 'do_not_touch_items', ['id'], unique=False)
    op.create_index(op.f('ix_do_not_touch_items_symbol'), 'do_not_touch_items', ['symbol'], unique=False)
    op.create_table('earnings_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('earnings_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_of_day', sa.String(length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.String(length=255), nullable=True),
    sa.Column('event_metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'earnings_datetime_utc', 'source', name='uq_earnings_events_symbol_datetime_source')
    )
    op.create_index(op.f('ix_earnings_events_earnings_datetime_utc'), 'earnings_events', ['earnings_datetime_utc'], unique=False)
    op.create_index(op.f('ix_earnings_events_id'), 'earnings_events', ['id'], unique=False)
    op.create_index(op.f('ix_earnings_events_symbol'), 'earnings_events', ['symbol'], unique=False)
    op.create_index('ix_earnings_events_symbol_datetime', 'earnings_events', ['symbol', 'earnings_datetime_utc'], unique=False)
    op.create_table('earnings_risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('next_earnings_datetime_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_to_earnings', sa.Integer(), nullable=True),
    sa.Column('earnings_within_window', sa.Boolean(), nullable=False),
    sa.Column('earnings_risk_window_days', sa.Integer(), nullable=True),
    sa.Column('earnings_before_expiration', sa.String(length=32), nullable=False),
    sa.Column('manual_option_expiration_date', sa.Date(), nullable=True),
    sa.Column('risk_label', sa.String(length=64), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_earnings_risk_snapshots_symbol_date')
    )
    op.create_index(op.f('ix_earnings_risk_snapshots_id'), 'earnings_risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_earnings_risk_snapshots_symbol'), 'earnings_risk_snapshots', ['symbol'], unique=False)
    op.create_index('ix_earnings_risk_snapshots_symbol_date', 'earnings_risk_snapshots', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('event_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('price_impact', sa.String(length=32), nullable=True),
    sa.Column('importance_assessment', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('key_points_json', sa.JSON(), nullable=True),
    sa.Column('risk_flags_json', sa.JSON(), nullable=True),
    sa.Column('affected_symbols_json', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(length=16), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.Text(), nullable=True),
    sa.Column('provider_type', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_analysis_event_id')
    )
    op.create_index(op.f('ix_event_analysis_event_id'), 'event_analysis', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_analysis_id'), 'event_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_event_analysis_symbol'), 'event_analysis', ['symbol'], unique=False)
    op.create_table('export_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_runs_id'), 'export_runs', ['id'], unique=False)
    op.create_table('failed_ticker_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_ticker_logs_data_category'), 'failed_ticker_logs', ['data_category'], unique=False)
    op.create_index(op.f('ix_failed_ticker_logs_id'), 'failed_ticker_logs', ['id'], unique=False)
    op.create_index(op.f('ix_failed_ticker_logs_symbol'), 'failed_ticker_logs', ['symbol'], unique=False)
    op.create_table('hard_filter_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('overall_decision', sa.String(length=32), nullable=False),
    sa.Column('option_decision', sa.String(length=32), nullable=False),
    sa.Column('outcomes_json', sa.JSON(), nullable=False),
    sa.Column('stock_blocking_labels_json', sa.JSON(), nullable=False),
    sa.Column('option_blocking_labels_json', sa.JSON(), nullable=False),
    sa.Column('warning_labels_json', sa.JSON(), nullable=False),
    sa.Column('skipped_filters_json', sa.JSON(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('stock_risk_reward', sa.Float(), nullable=True),
    sa.Column('price_extension_atr', sa.Float(), nullable=True),
    sa.Column('price_extension_sma50_percent', sa.Float(), nullable=True),
    sa.Column('regime_label', sa.String(length=32), nullable=True),
    sa.Column('earnings_risk_label', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_hard_filter_results_symbol_date')
    )
    op.create_index(op.f('ix_hard_filter_results_id'), 'hard_filter_results', ['id'], unique=False)
    op.create_index(op.f('ix_hard_filter_results_symbol'), 'hard_filter_results', ['symbol'], unique=False)
    op.create_index('ix_hard_filter_results_symbol_date', 'hard_filter_results', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('validation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_id'), 'import_runs', ['id'], unique=False)
    op.create_table('improvement_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('current_value', sa.String(length=128), nullable=True),
    sa.Column('proposed_value', sa.String(length=128), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('comparison_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_improvement_suggestions_id'), 'improvement_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_improvement_suggestions_status'), 'improvement_suggestions', ['status'], unique=False)
    op.create_index('ix_improvement_suggestions_type_status', 'improvement_suggestions', ['suggestion_type', 'status'], unique=False)
    op.create_table('insufficient_data_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insufficient_data_events_data_category'), 'insufficient_data_events', ['data_category'], unique=False)
    op.create_index(op.f('ix_insufficient_data_events_id'), 'insufficient_data_events', ['id'], unique=False)
    op.create_index(op.f('ix_insufficient_data_events_label'), 'insufficient_data_events', ['label'], unique=False)
    op.create_index(op.f('ix_insufficient_data_events_symbol'), 'insufficient_data_events', ['symbol'], unique=False)
    op.create_table('iv_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('atm_iv_30d', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_iv_history_symbol_date')
    )
    op.create_index(op.f('ix_iv_history_id'), 'iv_history', ['id'], unique=False)
    op.create_index(op.f('ix_iv_history_symbol'), 'iv_history', ['symbol'], unique=False)
    op.create_index('ix_iv_history_symbol_date', 'iv_history', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('iv_risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('current_iv', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('iv_percentile', sa.Float(), nullable=True),
    sa.Column('iv_history_days_used', sa.Integer(), nullable=True),
    sa.Column('iv_warning_threshold', sa.Float(), nullable=True),
    sa.Column('iv_reject_threshold', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(length=64), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_iv_risk_snapshots_symbol_date')
    )
    op.create_index(op.f('ix_iv_risk_snapshots_id'), 'iv_risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_iv_risk_snapshots_symbol'), 'iv_risk_snapshots', ['symbol'], unique=False)
    op.create_index('ix_iv_risk_snapshots_symbol_date', 'iv_risk_snapshots', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('learning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_type', 'period_start', 'period_end', name='uq_learning_reports_period')
    )
    op.create_index(op.f('ix_learning_reports_id'), 'learning_reports', ['id'], unique=False)
    op.create_table('market_regime_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_count', sa.Integer(), nullable=False),
    sa.Column('spy_close', sa.Float(), nullable=True),
    sa.Column('qqq_close', sa.Float(), nullable=True),
    sa.Column('iwm_close', sa.Float(), nullable=True),
    sa.Column('spy_trend', sa.String(length=16), nullable=False),
    sa.Column('qqq_trend', sa.String(length=16), nullable=False),
    sa.Column('iwm_trend', sa.String(length=16), nullable=False),
    sa.Column('index_uptrend_count', sa.Integer(), nullable=False),
    sa.Column('index_downtrend_count', sa.Integer(), nullable=False),
    sa.Column('vix_symbol', sa.String(length=32), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('vix_state', sa.String(length=16), nullable=False),
    sa.Column('yield_symbol', sa.String(length=32), nullable=True),
    sa.Column('yield_level', sa.Float(), nullable=True),
    sa.Column('yield_change_pct', sa.Float(), nullable=True),
    sa.Column('yield_state', sa.String(length=16), nullable=False),
    sa.Column('yield_pressure', sa.Boolean(), nullable=False),
    sa.Column('regime_label', sa.String(length=16), nullable=False),
    sa.Column('regime_score', sa.Integer(), nullable=False),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('insufficient_reasons_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', name='uq_market_regime_snapshots_date')
    )
    op.create_index('ix_market_regime_snapshots_date', 'market_regime_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_market_regime_snapshots_id'), 'market_regime_snapshots', ['id'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_memory_embeddings_source')
    )
    op.create_index(op.f('ix_memory_embeddings_id'), 'memory_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_memory_embeddings_symbol'), 'memory_embeddings', ['symbol'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('opportunity_lifecycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('current_state', sa.String(length=64), nullable=False),
    sa.Column('previous_state', sa.String(length=64), nullable=True),
    sa.Column('last_transition_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=True),
    sa.Column('user_review_status', sa.String(length=32), nullable=False),
    sa.Column('user_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reactivation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_opportunity_lifecycle_symbol')
    )
    op.create_index(op.f('ix_opportunity_lifecycle_id'), 'opportunity_lifecycle', ['id'], unique=False)
    op.create_index('ix_opportunity_lifecycle_review', 'opportunity_lifecycle', ['user_review_status'], unique=False)
    op.create_index('ix_opportunity_lifecycle_state', 'opportunity_lifecycle', ['current_state'], unique=False)
    op.create_index(op.f('ix_opportunity_lifecycle_symbol'), 'opportunity_lifecycle', ['symbol'], unique=False)
    op.create_table('opportunity_state_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('transition_reason_label', sa.String(length=128), nullable=False),
    sa.Column('transition_reason_summary', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('source_phase', sa.String(length=64), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_state_transitions_id'), 'opportunity_state_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_state_transitions_symbol'), 'opportunity_state_transitions', ['symbol'], unique=False)
    op.create_index('ix_opportunity_transitions_symbol_created', 'opportunity_state_transitions', ['symbol', 'created_at'], unique=False)
    op.create_table('option_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('manual_option_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('option_type', sa.String(length=16), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('contract_cost', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread_percent', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('iv_percent', sa.Float(), nullable=True),
    sa.Column('iv_state', sa.String(length=16), nullable=True),
    sa.Column('breakeven', sa.Float(), nullable=True),
    sa.Column('breakeven_distance_percent', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('target_margin_percent', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Integer(), nullable=True),
    sa.Column('suitability_label', sa.String(length=40), nullable=False),
    sa.Column('is_suitable', sa.Boolean(), nullable=False),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('rejection_labels_json', sa.JSON(), nullable=True),
    sa.Column('warning_labels_json', sa.JSON(), nullable=True),
    sa.Column('outcomes_json', sa.JSON(), nullable=True),
    sa.Column('earnings_risk_json', sa.JSON(), nullable=True),
    sa.Column('reasons_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manual_option_snapshot_id', name='uq_option_candidates_snapshot_id')
    )
    op.create_index(op.f('ix_option_candidates_id'), 'option_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_option_candidates_manual_option_snapshot_id'), 'option_candidates', ['manual_option_snapshot_id'], unique=True)
    op.create_index(op.f('ix_option_candidates_symbol'), 'option_candidates', ['symbol'], unique=False)
    op.create_index('ix_option_candidates_symbol_date', 'option_candidates', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('option_parser_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_option_parser_versions')
    )
    op.create_index(op.f('ix_option_parser_versions_id'), 'option_parser_versions', ['id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('key', name='uq_platform_settings_key')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_versions_name_version')
    )
    op.create_index(op.f('ix_prompt_versions_id'), 'prompt_versions', ['id'], unique=False)
    op.create_table('rejected_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('rejection_category', sa.String(length=64), nullable=False),
    sa.Column('rejection_severity', sa.String(length=32), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('is_rejected_but_interesting', sa.Boolean(), nullable=False),
    sa.Column('interesting_reasons_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_rejected_candidates_symbol_date')
    )
    op.create_index(op.f('ix_rejected_candidates_id'), 'rejected_candidates', ['id'], unique=False)
    op.create_index('ix_rejected_candidates_interesting', 'rejected_candidates', ['is_rejected_but_interesting'], unique=False)
    op.create_index(op.f('ix_rejected_candidates_symbol'), 'rejected_candidates', ['symbol'], unique=False)
    op.create_index('ix_rejected_candidates_symbol_date', 'rejected_candidates', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('rejection_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('price_data_available', sa.Boolean(), nullable=False),
    sa.Column('stock_return_pct', sa.Float(), nullable=True),
    sa.Column('would_stock_target_hit', sa.Boolean(), nullable=True),
    sa.Column('stop_hit', sa.Boolean(), nullable=True),
    sa.Column('bars_used', sa.Integer(), nullable=False),
    sa.Column('option_data_available', sa.Boolean(), nullable=False),
    sa.Column('would_option_have_worked', sa.String(length=16), nullable=False),
    sa.Column('was_rejection_correct', sa.Boolean(), nullable=True),
    sa.Column('is_too_strict', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('fed_to_memory', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', 'horizon_days', 'source_type', name='uq_rejection_outcomes_key')
    )
    op.create_index(op.f('ix_rejection_outcomes_id'), 'rejection_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_rejection_outcomes_symbol'), 'rejection_outcomes', ['symbol'], unique=False)
    op.create_index('ix_rejection_outcomes_symbol_date', 'rejection_outcomes', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('research_worklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worklist_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('worklist_type', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('final_action_label', sa.String(length=64), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=True),
    sa.Column('instrument_scope', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worklist_date', 'symbol', 'source', 'worklist_type', name='uq_worklist_date_symbol_source_type')
    )
    op.create_index(op.f('ix_research_worklist_items_id'), 'research_worklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_research_worklist_items_status'), 'research_worklist_items', ['status'], unique=False)
    op.create_index(op.f('ix_research_worklist_items_symbol'), 'research_worklist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_research_worklist_items_worklist_date'), 'research_worklist_items', ['worklist_date'], unique=False)
    op.create_index('ix_worklist_date_status', 'research_worklist_items', ['worklist_date', 'status'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('review_reason_label', sa.String(length=128), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('source_phase', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_id'), 'review_queue', ['id'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_index('ix_review_queue_status_priority', 'review_queue', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_review_queue_symbol'), 'review_queue', ['symbol'], unique=False)
    op.create_index('ix_review_queue_symbol_status', 'review_queue', ['symbol', 'status'], unique=False)
    op.create_table('review_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trigger_type', name='uq_review_triggers_symbol_type')
    )
    op.create_index('ix_review_triggers_active', 'review_triggers', ['is_active'], unique=False)
    op.create_index(op.f('ix_review_triggers_id'), 'review_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_review_triggers_symbol'), 'review_triggers', ['symbol'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_rule_versions_name_version')
    )
    op.create_index(op.f('ix_rule_versions_id'), 'rule_versions', ['id'], unique=False)
    op.create_table('sector_strength_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sector_symbol', sa.String(length=32), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('source_record_count', sa.Integer(), nullable=False),
    sa.Column('sector_return_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('relative_strength', sa.Float(), nullable=True),
    sa.Column('rs_rank', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('insufficient_reasons_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'sector_symbol', 'benchmark_symbol', name='uq_sector_strength_date_symbol_benchmark')
    )
    op.create_index('ix_sector_strength_date_symbol', 'sector_strength_snapshots', ['snapshot_date', 'sector_symbol'], unique=False)
    op.create_index(op.f('ix_sector_strength_snapshots_id'), 'sector_strength_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_sector_strength_snapshots_sector_symbol'), 'sector_strength_snapshots', ['sector_symbol'], unique=False)
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=True),
    sa.Column('instrument_scope', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('entry_reference_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('price_data_available', sa.Boolean(), nullable=False),
    sa.Column('stock_return_pct', sa.Float(), nullable=True),
    sa.Column('target_hit', sa.Boolean(), nullable=True),
    sa.Column('stop_hit', sa.Boolean(), nullable=True),
    sa.Column('bars_used', sa.Integer(), nullable=False),
    sa.Column('option_outcome_status', sa.String(length=40), nullable=False),
    sa.Column('option_return_pct', sa.Float(), nullable=True),
    sa.Column('manual_option_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('manual_trade_outcome', sa.String(length=32), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('fed_to_memory', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'signal_date', 'horizon_days', name='uq_signal_outcomes_symbol_date_horizon')
    )
    op.create_index(op.f('ix_signal_outcomes_id'), 'signal_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_signal_outcomes_symbol'), 'signal_outcomes', ['symbol'], unique=False)
    op.create_index('ix_signal_outcomes_symbol_date', 'signal_outcomes', ['symbol', 'signal_date'], unique=False)
    op.create_table('skill_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name', 'symbol', 'snapshot_date', name='uq_skill_links_key')
    )
    op.create_index(op.f('ix_skill_links_id'), 'skill_links', ['id'], unique=False)
    op.create_index(op.f('ix_skill_links_skill_name'), 'skill_links', ['skill_name'], unique=False)
    op.create_table('skill_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('skill_version', sa.String(length=32), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('target_hit_rate', sa.Float(), nullable=True),
    sa.Column('stop_first_rate', sa.Float(), nullable=True),
    sa.Column('stock_right_option_wrong_rate', sa.Float(), nullable=True),
    sa.Column('manual_option_reader_usefulness', sa.Float(), nullable=True),
    sa.Column('expected_value_proxy', sa.Float(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_performance_id'), 'skill_performance', ['id'], unique=False)
    op.create_index('ix_skill_performance_name', 'skill_performance', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skill_performance_skill_name'), 'skill_performance', ['skill_name'], unique=False)
    op.create_table('skill_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_index(op.f('ix_skill_registry_id'), 'skill_registry', ['id'], unique=False)
    op.create_table('skill_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name', 'version', name='uq_skill_versions_name_version')
    )
    op.create_index(op.f('ix_skill_versions_id'), 'skill_versions', ['id'], unique=False)
    op.create_index(op.f('ix_skill_versions_skill_name'), 'skill_versions', ['skill_name'], unique=False)
    op.create_table('stock_setup_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('setup_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('nearest_support', sa.Float(), nullable=True),
    sa.Column('nearest_resistance', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('regime_label', sa.String(length=16), nullable=True),
    sa.Column('sector_symbol', sa.String(length=32), nullable=True),
    sa.Column('sector_trend', sa.String(length=16), nullable=True),
    sa.Column('sector_rs_rank', sa.Integer(), nullable=True),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=True),
    sa.Column('components_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_stock_setup_signals_symbol_date')
    )
    op.create_index(op.f('ix_stock_setup_signals_id'), 'stock_setup_signals', ['id'], unique=False)
    op.create_index(op.f('ix_stock_setup_signals_symbol'), 'stock_setup_signals', ['symbol'], unique=False)
    op.create_index('ix_stock_setup_signals_symbol_date', 'stock_setup_signals', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('stock_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_count', sa.Integer(), nullable=False),
    sa.Column('current_close', sa.Float(), nullable=True),
    sa.Column('nearest_support', sa.Float(), nullable=True),
    sa.Column('nearest_resistance', sa.Float(), nullable=True),
    sa.Column('swing_low', sa.Float(), nullable=True),
    sa.Column('swing_high', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('stop_method', sa.String(length=32), nullable=False),
    sa.Column('risk_per_share', sa.Float(), nullable=True),
    sa.Column('reward_per_share', sa.Float(), nullable=True),
    sa.Column('stock_risk_reward', sa.Float(), nullable=True),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('insufficient_reasons_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_stock_setups_symbol_date')
    )
    op.create_index(op.f('ix_stock_setups_id'), 'stock_setups', ['id'], unique=False)
    op.create_index(op.f('ix_stock_setups_symbol'), 'stock_setups', ['symbol'], unique=False)
    op.create_index('ix_stock_setups_symbol_date', 'stock_setups', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('technical_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_count', sa.Integer(), nullable=False),
    sa.Column('last_close', sa.Float(), nullable=True),
    sa.Column('last_volume', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('volume_ratio_20', sa.Float(), nullable=True),
    sa.Column('data_sufficiency_status', sa.String(length=64), nullable=False),
    sa.Column('insufficient_indicators_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_technical_snapshots_symbol_date')
    )
    op.create_index(op.f('ix_technical_snapshots_id'), 'technical_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_technical_snapshots_symbol'), 'technical_snapshots', ['symbol'], unique=False)
    op.create_index('ix_technical_snapshots_symbol_date', 'technical_snapshots', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('ticker_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('final_action_label', sa.String(length=64), nullable=False),
    sa.Column('instrument_scope', sa.String(length=32), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=True),
    sa.Column('option_expression_status', sa.String(length=48), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sections_json', sa.JSON(), nullable=False),
    sa.Column('version_stamp_json', sa.JSON(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=True),
    sa.Column('profile_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_ticker_briefs_symbol_date')
    )
    op.create_index(op.f('ix_ticker_briefs_id'), 'ticker_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_ticker_briefs_symbol'), 'ticker_briefs', ['symbol'], unique=False)
    op.create_index('ix_ticker_briefs_symbol_date', 'ticker_briefs', ['symbol', 'snapshot_date'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('system_suggestion_label', sa.String(length=64), nullable=True),
    sa.Column('system_instrument_scope', sa.String(length=32), nullable=True),
    sa.Column('option_data_availability', sa.String(length=32), nullable=True),
    sa.Column('manual_option_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_actions_id'), 'user_actions', ['id'], unique=False)
    op.create_index(op.f('ix_user_actions_symbol'), 'user_actions', ['symbol'], unique=False)
    op.create_index('ix_user_actions_symbol_date', 'user_actions', ['symbol', 'action_date'], unique=False)
    op.create_table('rejection_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rejected_candidate_id', sa.Integer(), nullable=False),
    sa.Column('reason_label', sa.String(length=128), nullable=False),
    sa.Column('reason_category', sa.String(length=32), nullable=False),
    sa.Column('source_phase', sa.String(length=64), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rejected_candidate_id'], ['rejected_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejection_reasons_candidate_label', 'rejection_reasons', ['rejected_candidate_id', 'reason_label'], unique=False)
    op.create_index(op.f('ix_rejection_reasons_id'), 'rejection_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_rejection_reasons_rejected_candidate_id'), 'rejection_reasons', ['rejected_candidate_id'], unique=False)
    op.create_table('user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_action_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('override_type', sa.String(length=48), nullable=False),
    sa.Column('system_suggestion_label', sa.String(length=64), nullable=True),
    sa.Column('user_action_type', sa.String(length=32), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_action_id'], ['user_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_overrides_id'), 'user_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_user_overrides_symbol'), 'user_overrides', ['symbol'], unique=False)
    op.create_table('override_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_override_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('override_type', sa.String(length=48), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('outcome_classification', sa.String(length=24), nullable=False),
    sa.Column('stock_return_pct', sa.Float(), nullable=True),
    sa.Column('target_hit', sa.Boolean(), nullable=True),
    sa.Column('stop_hit', sa.Boolean(), nullable=True),
    sa.Column('price_data_available', sa.Boolean(), nullable=False),
    sa.Column('is_missed_opportunity', sa.Boolean(), nullable=False),
    sa.Column('is_avoided_correctly', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('fed_to_memory', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_override_id'], ['user_overrides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_override_outcomes_id'), 'override_outcomes', ['id'], unique=False)
    op.create_index('ix_override_outcomes_override', 'override_outcomes', ['user_override_id', 'horizon_days'], unique=False)
    op.create_index(op.f('ix_override_outcomes_symbol'), 'override_outcomes', ['symbol'], unique=False)
    # NOTE: autogenerate also proposed rewriting tickers' uq_tickers_symbol
    # constraint into a unique index (cosmetic ORM-vs-0001 drift). Both forms
    # enforce the same invariant, so that churn is intentionally omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_override_outcomes_symbol'), table_name='override_outcomes')
    op.drop_index('ix_override_outcomes_override', table_name='override_outcomes')
    op.drop_index(op.f('ix_override_outcomes_id'), table_name='override_outcomes')
    op.drop_table('override_outcomes')
    op.drop_index(op.f('ix_user_overrides_symbol'), table_name='user_overrides')
    op.drop_index(op.f('ix_user_overrides_id'), table_name='user_overrides')
    op.drop_table('user_overrides')
    op.drop_index(op.f('ix_rejection_reasons_rejected_candidate_id'), table_name='rejection_reasons')
    op.drop_index(op.f('ix_rejection_reasons_id'), table_name='rejection_reasons')
    op.drop_index('ix_rejection_reasons_candidate_label', table_name='rejection_reasons')
    op.drop_table('rejection_reasons')
    op.drop_index('ix_user_actions_symbol_date', table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_symbol'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_id'), table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index('ix_ticker_briefs_symbol_date', table_name='ticker_briefs')
    op.drop_index(op.f('ix_ticker_briefs_symbol'), table_name='ticker_briefs')
    op.drop_index(op.f('ix_ticker_briefs_id'), table_name='ticker_briefs')
    op.drop_table('ticker_briefs')
    op.drop_index('ix_technical_snapshots_symbol_date', table_name='technical_snapshots')
    op.drop_index(op.f('ix_technical_snapshots_symbol'), table_name='technical_snapshots')
    op.drop_index(op.f('ix_technical_snapshots_id'), table_name='technical_snapshots')
    op.drop_table('technical_snapshots')
    op.drop_index('ix_stock_setups_symbol_date', table_name='stock_setups')
    op.drop_index(op.f('ix_stock_setups_symbol'), table_name='stock_setups')
    op.drop_index(op.f('ix_stock_setups_id'), table_name='stock_setups')
    op.drop_table('stock_setups')
    op.drop_index('ix_stock_setup_signals_symbol_date', table_name='stock_setup_signals')
    op.drop_index(op.f('ix_stock_setup_signals_symbol'), table_name='stock_setup_signals')
    op.drop_index(op.f('ix_stock_setup_signals_id'), table_name='stock_setup_signals')
    op.drop_table('stock_setup_signals')
    op.drop_index(op.f('ix_skill_versions_skill_name'), table_name='skill_versions')
    op.drop_index(op.f('ix_skill_versions_id'), table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index(op.f('ix_skill_registry_id'), table_name='skill_registry')
    op.drop_table('skill_registry')
    op.drop_index(op.f('ix_skill_performance_skill_name'), table_name='skill_performance')
    op.drop_index('ix_skill_performance_name', table_name='skill_performance')
    op.drop_index(op.f('ix_skill_performance_id'), table_name='skill_performance')
    op.drop_table('skill_performance')
    op.drop_index(op.f('ix_skill_links_skill_name'), table_name='skill_links')
    op.drop_index(op.f('ix_skill_links_id'), table_name='skill_links')
    op.drop_table('skill_links')
    op.drop_index('ix_signal_outcomes_symbol_date', table_name='signal_outcomes')
    op.drop_index(op.f('ix_signal_outcomes_symbol'), table_name='signal_outcomes')
    op.drop_index(op.f('ix_signal_outcomes_id'), table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.drop_index(op.f('ix_sector_strength_snapshots_sector_symbol'), table_name='sector_strength_snapshots')
    op.drop_index(op.f('ix_sector_strength_snapshots_id'), table_name='sector_strength_snapshots')
    op.drop_index('ix_sector_strength_date_symbol', table_name='sector_strength_snapshots')
    op.drop_table('sector_strength_snapshots')
    op.drop_index(op.f('ix_rule_versions_id'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_review_triggers_symbol'), table_name='review_triggers')
    op.drop_index(op.f('ix_review_triggers_id'), table_name='review_triggers')
    op.drop_index('ix_review_triggers_active', table_name='review_triggers')
    op.drop_table('review_triggers')
    op.drop_index('ix_review_queue_symbol_status', table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_symbol'), table_name='review_queue')
    op.drop_index('ix_review_queue_status_priority', table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_worklist_date_status', table_name='research_worklist_items')
    op.drop_index(op.f('ix_research_worklist_items_worklist_date'), table_name='research_worklist_items')
    op.drop_index(op.f('ix_research_worklist_items_symbol'), table_name='research_worklist_items')
    op.drop_index(op.f('ix_research_worklist_items_status'), table_name='research_worklist_items')
    op.drop_index(op.f('ix_research_worklist_items_id'), table_name='research_worklist_items')
    op.drop_table('research_worklist_items')
    op.drop_index('ix_rejection_outcomes_symbol_date', table_name='rejection_outcomes')
    op.drop_index(op.f('ix_rejection_outcomes_symbol'), table_name='rejection_outcomes')
    op.drop_index(op.f('ix_rejection_outcomes_id'), table_name='rejection_outcomes')
    op.drop_table('rejection_outcomes')
    op.drop_index('ix_rejected_candidates_symbol_date', table_name='rejected_candidates')
    op.drop_index(op.f('ix_rejected_candidates_symbol'), table_name='rejected_candidates')
    op.drop_index('ix_rejected_candidates_interesting', table_name='rejected_candidates')
    op.drop_index(op.f('ix_rejected_candidates_id'), table_name='rejected_candidates')
    op.drop_table('rejected_candidates')
    op.drop_index(op.f('ix_prompt_versions_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_option_parser_versions_id'), table_name='option_parser_versions')
    op.drop_table('option_parser_versions')
    op.drop_index('ix_option_candidates_symbol_date', table_name='option_candidates')
    op.drop_index(op.f('ix_option_candidates_symbol'), table_name='option_candidates')
    op.drop_index(op.f('ix_option_candidates_manual_option_snapshot_id'), table_name='option_candidates')
    op.drop_index(op.f('ix_option_candidates_id'), table_name='option_candidates')
    op.drop_table('option_candidates')
    op.drop_index('ix_opportunity_transitions_symbol_created', table_name='opportunity_state_transitions')
    op.drop_index(op.f('ix_opportunity_state_transitions_symbol'), table_name='opportunity_state_transitions')
    op.drop_index(op.f('ix_opportunity_state_transitions_id'), table_name='opportunity_state_transitions')
    op.drop_table('opportunity_state_transitions')
    op.drop_index(op.f('ix_opportunity_lifecycle_symbol'), table_name='opportunity_lifecycle')
    op.drop_index('ix_opportunity_lifecycle_state', table_name='opportunity_lifecycle')
    op.drop_index('ix_opportunity_lifecycle_review', table_name='opportunity_lifecycle')
    op.drop_index(op.f('ix_opportunity_lifecycle_id'), table_name='opportunity_lifecycle')
    op.drop_table('opportunity_lifecycle')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_memory_embeddings_symbol'), table_name='memory_embeddings')
    op.drop_index(op.f('ix_memory_embeddings_id'), table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index(op.f('ix_market_regime_snapshots_id'), table_name='market_regime_snapshots')
    op.drop_index('ix_market_regime_snapshots_date', table_name='market_regime_snapshots')
    op.drop_table('market_regime_snapshots')
    op.drop_index(op.f('ix_learning_reports_id'), table_name='learning_reports')
    op.drop_table('learning_reports')
    op.drop_index('ix_iv_risk_snapshots_symbol_date', table_name='iv_risk_snapshots')
    op.drop_index(op.f('ix_iv_risk_snapshots_symbol'), table_name='iv_risk_snapshots')
    op.drop_index(op.f('ix_iv_risk_snapshots_id'), table_name='iv_risk_snapshots')
    op.drop_table('iv_risk_snapshots')
    op.drop_index('ix_iv_history_symbol_date', table_name='iv_history')
    op.drop_index(op.f('ix_iv_history_symbol'), table_name='iv_history')
    op.drop_index(op.f('ix_iv_history_id'), table_name='iv_history')
    op.drop_table('iv_history')
    op.drop_index(op.f('ix_insufficient_data_events_symbol'), table_name='insufficient_data_events')
    op.drop_index(op.f('ix_insufficient_data_events_label'), table_name='insufficient_data_events')
    op.drop_index(op.f('ix_insufficient_data_events_id'), table_name='insufficient_data_events')
    op.drop_index(op.f('ix_insufficient_data_events_data_category'), table_name='insufficient_data_events')
    op.drop_table('insufficient_data_events')
    op.drop_index('ix_improvement_suggestions_type_status', table_name='improvement_suggestions')
    op.drop_index(op.f('ix_improvement_suggestions_status'), table_name='improvement_suggestions')
    op.drop_index(op.f('ix_improvement_suggestions_id'), table_name='improvement_suggestions')
    op.drop_table('improvement_suggestions')
    op.drop_index(op.f('ix_import_runs_id'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index('ix_hard_filter_results_symbol_date', table_name='hard_filter_results')
    op.drop_index(op.f('ix_hard_filter_results_symbol'), table_name='hard_filter_results')
    op.drop_index(op.f('ix_hard_filter_results_id'), table_name='hard_filter_results')
    op.drop_table('hard_filter_results')
    op.drop_index(op.f('ix_failed_ticker_logs_symbol'), table_name='failed_ticker_logs')
    op.drop_index(op.f('ix_failed_ticker_logs_id'), table_name='failed_ticker_logs')
    op.drop_index(op.f('ix_failed_ticker_logs_data_category'), table_name='failed_ticker_logs')
    op.drop_table('failed_ticker_logs')
    op.drop_index(op.f('ix_export_runs_id'), table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_index(op.f('ix_event_analysis_symbol'), table_name='event_analysis')
    op.drop_index(op.f('ix_event_analysis_id'), table_name='event_analysis')
    op.drop_index(op.f('ix_event_analysis_event_id'), table_name='event_analysis')
    op.drop_table('event_analysis')
    op.drop_index('ix_earnings_risk_snapshots_symbol_date', table_name='earnings_risk_snapshots')
    op.drop_index(op.f('ix_earnings_risk_snapshots_symbol'), table_name='earnings_risk_snapshots')
    op.drop_index(op.f('ix_earnings_risk_snapshots_id'), table_name='earnings_risk_snapshots')
    op.drop_table('earnings_risk_snapshots')
    op.drop_index('ix_earnings_events_symbol_datetime', table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_symbol'), table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_id'), table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_earnings_datetime_utc'), table_name='earnings_events')
    op.drop_table('earnings_events')
    op.drop_index(op.f('ix_do_not_touch_items_symbol'), table_name='do_not_touch_items')
    op.drop_index(op.f('ix_do_not_touch_items_id'), table_name='do_not_touch_items')
    op.drop_index('ix_do_not_touch_items_expires', table_name='do_not_touch_items')
    op.drop_index('ix_do_not_touch_items_active', table_name='do_not_touch_items')
    op.drop_table('do_not_touch_items')
    op.drop_index('ix_do_not_touch_history_symbol_created', table_name='do_not_touch_history')
    op.drop_index(op.f('ix_do_not_touch_history_symbol'), table_name='do_not_touch_history')
    op.drop_index(op.f('ix_do_not_touch_history_id'), table_name='do_not_touch_history')
    op.drop_index(op.f('ix_do_not_touch_history_event_type'), table_name='do_not_touch_history')
    op.drop_table('do_not_touch_history')
    op.drop_index('ix_decision_snapshots_symbol_date', table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_symbol'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_id'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    op.drop_index('ix_decision_audit_symbol_date', table_name='decision_audit_metadata')
    op.drop_index(op.f('ix_decision_audit_metadata_symbol'), table_name='decision_audit_metadata')
    op.drop_index(op.f('ix_decision_audit_metadata_id'), table_name='decision_audit_metadata')
    op.drop_table('decision_audit_metadata')
    op.drop_index(op.f('ix_data_schema_versions_id'), table_name='data_schema_versions')
    op.drop_table('data_schema_versions')
    op.drop_index(op.f('ix_data_freshness_id'), table_name='data_freshness')
    op.drop_index(op.f('ix_data_freshness_data_category'), table_name='data_freshness')
    op.drop_table('data_freshness')
    op.drop_index('ix_case_memory_symbol_type', table_name='case_memory')
    op.drop_index(op.f('ix_case_memory_symbol'), table_name='case_memory')
    op.drop_index(op.f('ix_case_memory_id'), table_name='case_memory')
    op.drop_table('case_memory')
    op.drop_index(op.f('ix_ai_providers_provider_key'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index('ix_action_suggestions_symbol_date', table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_symbol'), table_name='action_suggestions')
    op.drop_index(op.f('ix_action_suggestions_id'), table_name='action_suggestions')
    op.drop_table('action_suggestions')
    # ### end Alembic commands ###