from enum import Enum


class DataSufficiencyLabel(str, Enum):
    SUFFICIENT = "SUFFICIENT"

    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    INSUFFICIENT_OPTION_DATA = "INSUFFICIENT_OPTION_DATA"
    INSUFFICIENT_NEWS_DATA = "INSUFFICIENT_NEWS_DATA"
    INSUFFICIENT_IV_DATA = "INSUFFICIENT_IV_DATA"
    INSUFFICIENT_EARNINGS_DATA = "INSUFFICIENT_EARNINGS_DATA"
    INSUFFICIENT_MEMORY_DATA = "INSUFFICIENT_MEMORY_DATA"
    INSUFFICIENT_PRICE_HISTORY = "INSUFFICIENT_PRICE_HISTORY"


class DataFreshnessStatus(str, Enum):
    FRESH = "FRESH"
    STALE = "STALE"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class DataQualitySeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKING = "BLOCKING"