from enum import Enum


class DataSufficiencyLabel(str, Enum):
    SUFFICIENT = "SUFFICIENT"

    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    INSUFFICIENT_OPTION_DATA = "INSUFFICIENT_OPTION_DATA"
    INSUFFICIENT_NEWS_DATA = "INSUFFICIENT_NEWS_DATA"
    INSUFFICIENT_IV_DATA = "INSUFFICIENT_IV_DATA"
    INSUFFICIENT_EARNINGS_DATA = "INSUFFICIENT_EARNINGS_DATA"
    INSUFFICIENT_MEMORY_DATA = "INSUFFICIENT_MEMORY_DATA"
    INSUFFICIENT_PRICE_HISTORY = "INSUFFICIENT_PRICE_HISTORY"
    INSUFFICIENT_FILING_DATA = "INSUFFICIENT_FILING_DATA"
    INSUFFICIENT_MACRO_DATA = "INSUFFICIENT_MACRO_DATA"
    INSUFFICIENT_INDICATOR_DATA = "INSUFFICIENT_INDICATOR_DATA"
    INSUFFICIENT_IV_HISTORY = "INSUFFICIENT_IV_HISTORY"
    IV_DATA_NOT_AVAILABLE = "IV_DATA_NOT_AVAILABLE"
    EARNINGS_DATA_NOT_AVAILABLE = "EARNINGS_DATA_NOT_AVAILABLE"
    INSUFFICIENT_SETUP_DATA = "INSUFFICIENT_SETUP_DATA"


class DataFreshnessStatus(str, Enum):
    FRESH = "FRESH"
    STALE = "STALE"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class DataQualitySeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKING = "BLOCKING"