"""Phase 26, step 26.12 — Review Queue dashboard page.

Streamlit page that shows the pending review queue, with per-item
resolve / dismiss / in-review actions, plus a button to run the
trigger job on demand. Loaded only by ``streamlit run``.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import requests  # noqa: E402
import streamlit as st  # noqa: E402

from app.core.config import get_settings  # noqa: E402

settings = get_settings()
st.set_page_config(
    page_title=f"{settings.app_name} — Review Queue", layout="wide"
)
st.title("Review Queue")
st.caption(
    "Pending review items generated by the next-review-trigger engine. "
    "The new RECHECK_AFTER_MANUAL_OPTION_INPUT trigger appears here once a "
    "manual option contract is pasted for a symbol in WAIT_FOR_MANUAL_OPTION_INPUT."
)


def _get(path: str, **params) -> dict | None:
    try:
        response = requests.get(
            f"{settings.api_base_url}{path}", params=params, timeout=15
        )
    except requests.RequestException as exc:
        st.warning(f"Failed: {exc}")
        return None
    if response.status_code != 200:
        st.warning(f"{path} returned status {response.status_code}.")
        return None
    return response.json()


def _post(path: str, body: dict | None = None) -> dict | None:
    try:
        response = requests.post(
            f"{settings.api_base_url}{path}", json=body or {}, timeout=15
        )
    except requests.RequestException as exc:
        st.warning(f"Failed: {exc}")
        return None
    if response.status_code != 200:
        st.warning(f"{path} returned status {response.status_code}.")
        return None
    return response.json()


# --- Run job --------------------------------------------------------------

if st.button("Run trigger evaluation now"):
    result = _post("/api/review-queue/run-triggers", {})
    if result is not None:
        body = result["result"]
        st.success(
            f"Processed {body['result']['symbols_processed']} symbol(s); "
            f"created {body['result']['queue_items_created']} item(s), "
            f"refreshed {body['result']['queue_items_refreshed']} item(s)."
        )

# --- Filters --------------------------------------------------------------

st.subheader("Pending items")

status_filter = st.selectbox(
    "Status filter",
    options=["(active)", "PENDING", "IN_REVIEW", "RESOLVED", "DISMISSED"],
)
params: dict = {}
if status_filter != "(active)":
    params["status"] = status_filter
listing = _get("/api/review-queue", **params)

if listing is not None:
    rows = listing.get("items", [])
    if not rows:
        st.info("No queue items match the current filter.")
    else:
        st.dataframe(
            [
                {
                    "ID": row["id"],
                    "Symbol": row["symbol"],
                    "Trigger": row["trigger_type"],
                    "Priority": row["priority"],
                    "Status": row["status"],
                    "Reason": row["review_reason_label"],
                    "Summary": row["summary"],
                    "Lifecycle": row["lifecycle_state"] or "—",
                    "Created": row["created_at"],
                }
                for row in rows
            ],
            use_container_width=True,
        )

st.divider()

# --- Per-item actions -----------------------------------------------------

st.subheader("Resolve / Dismiss an item")
queue_id = st.number_input("Queue item ID", min_value=1, step=1)
notes = st.text_input("Notes (optional)")

col_resolve, col_dismiss, col_in_review, col_reopen = st.columns(4)

with col_resolve:
    if st.button("Resolve"):
        result = _post(
            f"/api/review-queue/items/{int(queue_id)}/resolve",
            {"notes": notes} if notes else {},
        )
        if result is not None:
            st.success(f"Resolved item {queue_id}.")

with col_dismiss:
    if st.button("Dismiss"):
        result = _post(
            f"/api/review-queue/items/{int(queue_id)}/dismiss",
            {"notes": notes} if notes else {},
        )
        if result is not None:
            st.success(f"Dismissed item {queue_id}.")

with col_in_review:
    if st.button("Mark IN_REVIEW"):
        result = _post(f"/api/review-queue/items/{int(queue_id)}/in-review", {})
        if result is not None:
            st.success(f"Marked {queue_id} IN_REVIEW.")

with col_reopen:
    if st.button("Reopen"):
        result = _post(f"/api/review-queue/items/{int(queue_id)}/reopen", {})
        if result is not None:
            st.success(f"Reopened {queue_id}.")

# --- Armed triggers -------------------------------------------------------

st.subheader("Armed triggers")
arm_listing = _get("/api/review-queue/triggers")
if arm_listing is not None and arm_listing.get("triggers"):
    st.dataframe(
        [
            {
                "Symbol": t["symbol"],
                "Type": t["trigger_type"],
                "Lifecycle": t["lifecycle_state"] or "—",
                "Active": t["is_active"],
                "Last evaluated": t["last_evaluated_at"] or "—",
                "Last fired": t["last_fired_at"] or "—",
                "Fire count": t["fire_count"],
            }
            for t in arm_listing["triggers"]
        ],
        use_container_width=True,
    )
else:
    st.info("No armed triggers.")
